algoo/preview-generator

- preview_generator/manager.py
- preview_generator/preview/builder/document__scribus.py
- preview_generator/preview/builder/document_generic.py
- preview_generator/preview/builder/image__imconvert.py
- preview_generator/preview/builder/image__inkscape.py
- preview_generator/preview/builder/image__pillow.py
- preview_generator/preview/builder/image__wand.py
- preview_generator/preview/builder/office__libreoffice.py
- preview_generator/preview/builder/pdf__pypdf2.py
- preview_generator/preview/generic_preview.py
- setup.py
- tests/input/jpeg/test_jpeg.py
- tests/input/txt/test_txt.py
Adds mimetype for functions working with file given as a stream and no extension.
> handles no extension given for office builder and scribus builder

- preview_generator/exception.py
- preview_generator/preview/builder/document_generic.py
- preview_generator/preview/builder/office__libreoffice.py
- preview_generator/preview/builder/pdf__pypdf2.py
- preview_generator/preview/generic_preview.py
- tests/builders/test_libreoffice_builder.py
> optional mimetype + test for libreoffice builder

- preview_generator/manager.py
- preview_generator/preview/builder/archive__zip.py
- preview_generator/preview/builder/document_generic.py
- preview_generator/preview/builder/image__imconvert.py
- preview_generator/preview/builder/image__inkscape.py
- preview_generator/preview/builder/image__pillow.py
- preview_generator/preview/builder/image__wand.py
- preview_generator/preview/builder/pdf__pypdf2.py
- preview_generator/preview/builder/plain_text.py
- preview_generator/preview/generic_preview.py
- tests/input/binary/test_binary.py
- tests/input/bmp/test_bmp.py
- tests/input/eps/test_eps.py
- tests/input/gif/test_gif.py
- tests/input/jpeg/test_jpeg.py
- tests/input/odt/test_odt.py
- tests/input/pdf/test_pdf.py
- tests/input/png/test_png.py
- tests/input/sla/test_sla.py
- tests/input/svg/test_svg.py
- tests/input/txt/test_txt.py
- tests/input/xcf/test_xcf.py
- tests/input/xlsx/test_xlsx.py
- tests/input/zip/test_zip.py
> add_has_methods_for_all_type_of_preview_and_update_test

- preview_generator/manager.py
- preview_generator/preview/builder_factory.py
> add RLock to get_instance of PreviewBuilderFactory

- preview_generator/preview/builder/pdf__pypdf2.py
> fix_read_write_concurrency_with_page_number_on_pdf

- preview_generator/file_converter.py
- preview_generator/manager.py
- preview_generator/preview/builder/archive__zip.py
- preview_generator/preview/builder/document__scribus.py
- preview_generator/preview/builder/image__pillow.py
- preview_generator/preview/builder/image__wand.py
- preview_generator/preview/builder/office__libreoffice.py
- preview_generator/preview/builder_factory.py
- preview_generator/preview/generic_preview.py
- preview_generator/preview/scripts/scribus_sla_to_pdf.py
- preview_generator/utils.py
> replace print and root log to preview_generator log

- preview_generator/preview/builder/office__libreoffice.py
> disable odb file support for libreoffice

- README.rst
- preview_generator/infos.py
Removes bad imports in readme and changes usages to give more specific examplles of code
> Fix/69  errors in readme

- README.rst
> add qpdf to dependencies

- .travis.yml
- README.rst
- setup.py
- tests/input/odt/test_odt.py
related to #91 
- remove python 3.4 support
- add python 3.7 support for tests (which mean many change in travis to make things works)
> Fix/91 remove python 3.4 support and replace to 3.7

- README.rst
- preview_generator/preview/builder/image__pillow.py
POC to have better preview generation using pillow,
This fix issue related to B&W file (#84) and use better jpg save choice (progressive jpeg, quality, better resampling).
we should decide default config (and maybe think about making this configurable)
> Fix/84  better pillow preview generation

- preview_generator/preview/builder/document_generic.py
- preview_generator/preview/builder/image__imconvert.py
- preview_generator/preview/builder/image__inkscape.py
- preview_generator/preview/builder/image__pillow.py
- preview_generator/preview/builder/image__wand.py
- preview_generator/preview/builder/pdf__pypdf2.py
- preview_generator/preview/generic_preview.py
See: https://github.com/algoo/preview-generator/pull/100/files#r303397097
> Make the size parameter optional, as advertised.

- .travis.yml
- README.rst
- tests/input/bmp/test_bmp.py
> better exiftool install

- .editorconfig
- .gitignore
- pyproject.toml
> Fix/133  add dotfiles

- .travis.yml
- README.rst
- contribute.rst
- preview_generator/preview/builder/video__ffmpeg.py
- preview_generator/utils.py
- setup.cfg
- setup.py
- tests/input/ogg_theora/test_ogg_theora_ffmpeg.py
Implement support of video files preview based on ffmpeg.
preview is available as paginated jpeg preview (10 frames) + json extract of metadata (stream data, file metadata)
> first support for FFMPEG-based preview of video files

- preview_generator/preview/builder/image__cairosvg.py
- preview_generator/preview/builder/image__inkscape.py
> support image/svg mimetype

- preview_generator/manager.py
> repair handling of file with file_extension

- preview_generator/preview/builder/video__ffmpeg.py
- preview_generator/preview/builder_factory.py
> Fix/149  better mimetype support for video with ffmpeg

- preview_generator/preview/builder/cad__vtk.py
- preview_generator/preview/builder/image__imconvert.py
- preview_generator/preview/builder/image__inkscape.py
Fix https://github.com/algoo/preview-generator/issues/160
> Remove tmp file after usage

- .travis.yml
- README.rst
> Fix/163  fix x vtk issue with xvfb

- .pre-commit-config.yaml
- .travis.yml
- preview_generator/manager.py
- preview_generator/preview/builder/office__libreoffice.py
- preview_generator/preview/builder/video__ffmpeg.py
- preview_generator/utils.py
- setup.cfg
- setup.py
- tests/builders/test_libreoffice_builder.py
- tests/test_manager.py
related to #187
POC for FileLock.
This current does :
- Refactor manager with previewContext to limit code duplication
- Add filelock at manager level
- set ffmpeg to overwrite mode
- add filelock for libreoffice too
- add support for isort 5.* (to fix ci)
> Feature/187  add filelock to avoid create multiple same preview

- contribute.rst
- preview_generator/manager.py
- preview_generator/preview/builder/cad__vtk.py
- preview_generator/preview/builder/office__libreoffice.py
- preview_generator/preview/builder_factory.py
- preview_generator/preview/generic_preview.py
- setup.py
- tests/fixtures/coderunnerbuilder.py
- tests/test_locks.py
> Fix/190  test locking

- preview_generator/preview/builder/document_generic.py
- tests/input/odt/test_odt.py
- tests/input/pdf/test_pdf.py
related to #194 
- Hack to make one page preview working correctly.
> Transform stream in order to make pdf one page preview work

- CHANGELOG.rst
- preview_generator/preview/builder/office__libreoffice.py
Which was not properly terminated in all cases.
> fix: always terminate libreoffice process

- preview_generator/manager.py
- preview_generator/preview/builder/document_generic.py
- preview_generator/preview/builder/image__wand.py
> properly create preview with pdf pivot

- preview_generator/manager.py
- preview_generator/preview/builder/document_generic.py
- tests/input/odt/test_odt.py
- tests/input/pdf/test_pdf.py
- tests/input/xlsx/test_xlsx.py
fix the issue #224
fix also the page_number part of https://github.com/algoo/preview-generator/issues/222#issuecomment-832729388
> pdf pivot file should have always pdf extension

- preview_generator/preview/builder/image__wand.py
- preview_generator/preview/builder/pdf__pypdf2.py
- preview_generator/preview/builder_factory.py
- tests/test_builder_factory.py
> disable wand builder by default

- .pre-commit-config.yaml
- .travis.yml
- README.rst
- contribute.rst
- preview_generator/preview/builder/document__drawio.py
- preview_generator/preview/builder/document__scribus.py
- preview_generator/preview/builder/image__cairosvg.py
- preview_generator/preview/builder/video__ffmpeg.py
- setup.cfg
- setup.py
- tests/input/stl/test_stl_vtk.py
> Fix/233  make some builders not required

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
Add github templates to make life a bit easier for : 
- maintainer
- external contributors
> add issues and pr templates
